nelmio_api_doc:
    documentation:
        servers:
            - url: '%env(APP_URL)%'
              description: App Environment
            - url: 'http://localhost'
              description: Default
        info:
            title: '%env(APP_NAME)%'
            description: '%env(APP_DESCRIPTION)%'
            version: '%env(APP_VERSION)%'
        components:
            securitySchemes:
                Bearer:
                    in: header
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
#        security:
#            - Bearer: []

    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/doc) # Accepts routes under /api except /api/doc
